### ISSUE TITLE
How much error handling should the SDK do before requests are sent to the Transfer API?

### ISSUE THREAD

**Issue by sirosen** [globusonline/globus-sdk-python#14]
@jimPruyne mentioned in #13 that he thinks (or at least thought at one time) that the SDK should catch `label=''` before a task is submitted to the Transfer API.
This is part of a more general class of feature, which is handling for invalid requests to the Transfer API prior to API interactions.

I think this *only* applies to Transfer, since it's our oldest and most mature API, so others should just rely on non-200 responses for now.
Even if you don't agree, please keep this particular issue focused only on our handling of the Transfer API.
Otherwise, there are many rabbit holes and we might not be able to drive this to resolution.

I actually created an error class for this exact type of error handling (perhaps poorly named as `InvalidDocumentBodyError`), but it's currently unused because I stripped out the code that was triggering it.

In the particular case of `label=''` for a Task, I don't think the SDK should do validation.
It's a fairly subtle and non-generalizable error specific to task submission, and I don't see that a single request to the API matters much.
However, it becomes more of a concern if we think that a lot of work might be done between assembling the Task document and task submission.
Causing an error when `label=''`, or perhaps when paths do or do not have requisite trailing slashes, would, in that case, move the failure to be earlier.
I'm not really convinced that's a likely scenario and important use case on which to focus.

There are some potential areas for this type of handling that make a bit more sense client-side. That could be because the SDK has a better idea of what went wrong and how to fix it in an SDKish way, or because it's not the same kind of error (or even an error at all) when it arrives at the API.
Some examples, in no particular order,

- POST body has wrong `DATA_TYPE` for the API endpoint, possibly recommend using a relevant `make_X_data` helper
- Transfer Task is missing submission ID, also recommend using `make_X_data` helper
- Non-UUID string supplied in a field that must be a UUID (e.x. endpoint ID). This often results in a 404 from the API because the requested resource doesn't exist, but the SDK could treat as "invalid" and throw a different error.
- Similar, attempt to use canonical endpoint name for a call that only supports endpoint IDs

Although there will always be exceptions to our rules, we shouldn't be handling these decisions on a pure case-by-case basis.
There's a little bit of bleed-over into this issue from the fact that the Transfer API gives 404s for certain requests which are definitively "wrong", like `GET /endpoint/nonuuidstring`, whereas maybe those should result in 400 Bad Request.

One of the stronger cases for more SDK error handling is that of invalid documents for Transfer Tasks, which suggest that the user isn't relying on `make_submit_transfer_data`. The API can't possibly know this, since it doesn't know what the client is (unless we add logic to the API pertaining to a custom user agent and use that agent in the SDK).
Should we do more client-side error detection for this class of errors?

**Comment by bd4** [comment]
I still don't think it's worth it. It's great now when everyone is contributing, but it's quite possible that this halcyon world will end, and I'll be the one stuck with maintaining at least the Transfer part of the SDK. I really really don't want to have to maintain API side error handling and detailed SDK side error handling. I see your point that you could provide a nicer message, like recommending to use make_X_data helpers, but that is a very icing on cake feature to me, and not worth the maintenance cost at this point. Having good documentation is much higher priority.

**Comment by bd4** [comment]
To answer the question in the title: none.

**Comment by bd4** [comment]
As a point of design philosophy, I think if you want detailed client side verification, SOAP or XMLRPC is a much better choice than REST. You basically get the verification for free in every language. I don't think client side verification makes sense for REST - exposing the errors returned by the API should be sufficient.

**Comment by jimPruyne** [comment]
I'm not really sure how SOAP/XMLRPC vs. REST makes a difference in client side error handling, but we don't need to go down that hole either. I prefer the general design philosophy of handling errors as close as possible to where they occur. But, I also see the value in not solving the same problem twice (esp. since they can then get out of sync. with each other), and I agree that decisions should lie with those who ultimately must maintain it, so I'm not going to argue strongly one way or the other.

**Comment by sirosen** [comment]
I've been trying to figure out if there's a case for this, to serve as a counterpoint to Bryce's answer.
Ultimately, I wasn't able to convince myself when writing up this issue, and I'm not able to convince myself now either.

Letting an API error come back as a python exception is just so much easier and has such a strong consistency advantage that I can't make this seem worth it in my head.

Closing this out.
