### ISSUE TITLE
Add PendingDeprecationWarnings to Nexus Client (but where?)

### ISSUE THREAD

**Issue by sirosen** [globusonline/globus-sdk-python#2]
We mentioned this in the comments on #1 

We want anyone who starts using `globus_sdk.NexusClient` to be aware that any and all features offered there are going away in the not-too-distant future.
This seems like an appropriate place for `PendingDeprecationWarning`s to come into play.

I think that we should have a single warning for the entire client in its initializer, with something along the lines of

```python
warnings.warn(
    ('Globus Nexus provides access to features of Globus which are '
     'being moved to new services. If you use Nexus, be aware that '
     'Globus plans to deprecate the API in 2016, and you should stop '
     'using it before 2017'),
    PendingDeprecationWarning)
```

How long should the warning be, and what should it say? Do we want to commit in the warning to a timeline?

I feel comfortable saying we'll be done with Nexus in 2017, given that we only need to kill the requirement for GOAuth tokens to do it.

**Comment by bd4** [comment]
I didn't realize python had a pending deprecation, that is perfect for our purposes. Agreed it should be in the initializer. This is what we used in the docs:
http://docs.staging.globuscs.info/api/transfer/overview/#authentication

Which is purposely vague about exact timelines. How about this:
warnings.warn(
    ('Globus Nexus provides access to features of Globus which are '
     'being moved to new services. If you use Nexus, be ready to '
     'transition to the new API after we announce it's availability.'),
    PendingDeprecationWarning)

@ranantha what do you think?

**Comment by sirosen** [comment]
I'll happily add that, pending approval from Rachana.

**Comment by ranantha** [comment]
If two-legged OAuth (using Globus ID) is supported in Globus Auth by the time this client is released, do we need the SDK to continue to support Nexus APIs? 

If we do want to keep client code to Nexus, suggested text below:

"Functionality provided by Globus Nexus for authentication has been upgraded, and now available under Globus Auth. Globus Nexus will continue to be supported for some time for backwards compatibility purposes, but will be deprecated shortly. Application developers should plan to transition to Globus Auth API."

**Comment by bd4** [comment]
Well the client is already available in the sense that it's in a public git repo. Maybe in a week it will be ready to publicize, e.g. change the docs to point at it instead of the old lib, and send a message to the mailing list about it. We can always update it again once 2-legged is ready for real in auth.

**Comment by sirosen** [comment]
@ranantha it's important to note that this isn't a matter of backward compatibility.
We need the `NexusClient` for work on the SDK and CLI to move forward without being blocked on 2-legged in Globus Auth.

I don't know that the SDK or CLI will support Nexus when they're initially published -- as you suggested, I think we should drop it before starting to treat these as fully-fledged products.
This is not really a big deal, since this code is destined for the scrap heap, but in case it does leak out the door, I want the warning in place.
We could go with Bryce's text, which is true today, or with your suggested text, which we hope will be true by the time anyone sees this.
I'm kind of uncomfortable with the latter, since this repo (along with this conversation, btw) is public, and people can already look at this code.

**Comment by ranantha** [comment]
@sirosen either text is fine with me for now.

Let's revisit the wording depending on where we are when we announce a supported client SDK in production.
