### ISSUE TITLE
Support Loading Token when Instantiating a Client

### ISSUE THREAD

**Issue by sirosen** [globusonline/globus-sdk-python#4]
After some thought about this, I think this should be an SDK responsibility.
I think that we should have an option somewhere in `~/.globus.cfg` for this, but also maybe an option in the client initializers.

Here's the issue: if I write code that talks to multiple APIs, I'll end up having a bunch of cases in which I instantiate the clients myself.
There are a couple of tempting options for how to pass an auth token to all of them uniformly, but they all seem worse than having this in the SDK itself.

People will write (with varying degrees of correctness) something like

```python
def make_clients(token):
    ac, nc, tc = AuthClient(), NexusClient(), TransferClient()
    for c in (ac, nc, tc):
        c.set_auth_token(token)
    return ac, nc, tc
```

because so many calls must be authenticated.

I'd rather see `set_auth_token` be invoked if you pass `auth_token=...` to the constructor.
However, better yet, I'd like for the SDK itself to support loading the auth token from a file, like `~/.globus.cfg`.

We could tell people to define something like
```ini
[default]
auth_token = ABC123

[environment beta]
auth_token = DEF456
```

That would make the simplest possible config file
```ini
auth_token = GHI789
```

I think that's appealingly simple.

I'm fighting hard to make sure that the CLI isn't just a re-implementation of curl, and I think handling the token outside of the SDK pushes me to make some compromises, like adding `--headers` to handle this.

@bd4 What do you think of this?
I think the ideal is that you can put it in a config file or an environment variable and things just work.
It only gets tricky when you want to support multiple tokens for multiple environments (which, of course, is something of an internal must).

**Comment by bjmc** [comment]
Access tokens are going to be short-lived, so putting them in config files and updated them sounds like a sisyphean endeavor to me.

Maybe it would make sense for the SDK to take a refresh token in a config file and automatically handle periodically exchanging it for fresh access tokens for you.

**Comment by sirosen** [comment]
Today, GOAuth tokens are not short lived, and don't have refresh tokens.
I'm interested in building something that works today, but will serve as a basis for loading whatever the *real* credentials will be.
This is something of a stopgap measure, but we can convert it to load a refresh token or maybe even 2-legged oauth credentials.
I was going to build a wrapper that does this a bit for the CLI because the SDK doesn't have a good credential loading mechanism, but then I thought it would be better to implement here.

I understand the desire to not build throwaway features for interacting with Nexus, but I also want to be pragmatic about this.
@bjmc would adding a `PendingDeprecationWarning` that gets triggered when you set `auth_token` in the config be satisfactory to you? It could mirror the warning described by #3 more or less.
Keep in mind that there's no support commitment on this code of any kind yet -- we can add or remove whatever is most convenient for us to use, and not worry about breaking anyone else.

**Comment by bd4** [comment]
This all sounds good to me. We can start with goauth token, and evolve it as needed.
