### ISSUE TITLE
Establish a consistent pattern of Data Dict vs. GlobusResponse for client return values

### ISSUE THREAD

**Issue by sirosen** [globusonline/globus-sdk-python#9]
I've complicated our situation with regard to client methods by introducing the iterators.
Any iterable call yields dictionary objects consisting of individual documents.
That works out really tidily for the Transfer API, where you get an iterator of dicts with `DATA_TYPE` on each one of them, and everyone is happy.

However, things really start to fall apart when we go back to non-iterable calls.
Those calls used to return a `GlobusResponse` object, but now they can optionally return data dicts.

For example, `TransferClient.get_endpoint()` returns a `GlobusResponse`, but `AuthClient.get_identities()` returns a `dict`.

I'm not really concerned about `NexusClient.get_goauth_token()` because that's deprecated and slated for removal.
I just want us to be consistent among the calls that don't have a behavior that forbids them from returning `GlobusResponse`.

Since some calls won't have a valid `json_body` attribute (e.x. they return raw text or HTML), I think the best approach is that we have two forms of calls

  1. Is iterable, every item in the iterator is a `dict`
  2. Is not iterable, return type is `GlobusResponse`

Does this seem acceptable? Having a mix of `GlobusResponse` some places and `GlobusResponse.json_body` in others has confused me a couple of times, and will likely do the same for others.

An alternative is to actually wrap the results of iterable calls in artificial `GlobusResponse` objects -- I'm not at all opposed to this, if we want to do that, so long as we do it *everywhere*.

**Comment by bd4** [comment]
`TransferClient.get_endpoint()` returns a `GlobusResponse` because it's old and I haven't gotten around to changing it to return a dict. For Transfer, I think returning an iterator or dict works for everything. For the cases in auth that aren't JSON, could we just return text body?

I'm also open to the idea of GlobusResponse everywhere, and wrapping the iter somehow, but I prefer returning the actual data, in whatever format it happens to be in, if that doesn't cause too many uniformity problems. I'm less fond of iter/GlobusResponse combo.

**Comment by sirosen** [comment]
I discussed this a bit with Borja, as an abstract problem, to get another opinion about library behaviors.
He said he would prefer that a library gives him objects to raw dicts, which I intuitively agree with.

What about having a new type, GlobusData, from which GlobusResponse might inherit (not necessarily, I'm unsure here), and wrapping iterator responses in that? It also allows us to dangle some metadata off of those objects, like their offset in a result set.

**Comment by bd4** [comment]
Ok works for me. Maybe we could make the default __str__ just pretty print the data dict, so it's more friendly to use with ipython.

**Comment by sirosen** [comment]
I'll take a crack at this, and I agree that having a good `__repr__` and a good `__str__` would be really useful.

I like the fact that wrapping all of our return values in simple objects lets us add on attributes without breaking existing client code, even if we don't need that functionality today.

Considering my question answered and this discussion closed. :smile:
